[package]
name = "whatawm"
version = "0.1.0"
authors = ["Lex Childs <lexchilds@gmail.com>"]
edition = "2018"

[lib]
name = "whata"
path = "src/lib.rs"

[[bin]]
name = "whatawm"
path = "src/wm.rs"

[dependencies]
x11-dl = "2.18.3"
toml = "0.4.10"
serde = "*"
serde_derive = "*"
xdg = "2.2.0"
