[package]
name = "leftwm"
version = "0.1.4"
authors = ["Lex Childs <lexchilds@gmail.com>"]
edition = "2018"

[lib]
name = "leftwm"
path = "src/lib.rs"

[dependencies]
x11-dl = "2.18.3"
toml = "0.4.10"
colored = "1.7"
serde = "*"
serde_derive = "*"
xdg = "2.2.0"
signal-hook = "0.1.7"
env_logger = "0.6.1"
log = "0.4.0"
dirs = "1.0.5"
